# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: get_data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eget_data.proto\x12\tdevice.v1\" \n\x0fIdentifyRequest\x12\r\n\x05Token\x18\x01 \x01(\t\"\n\n\x08GetState\"\t\n\x07GetInfo\",\n\x08SetState\x12 \n\x05state\x18\x01 \x01(\x0e\x32\x11.device.v1.States\"\xf2\x01\n\x05State\x12(\n\x08light_on\x18\x01 \x01(\x0e\x32\x16.device.v1.LightStates\x12,\n\tdoor_lock\x18\x02 \x01(\x0e\x32\x19.device.v1.DoorLockStates\x12+\n\tchannel_1\x18\x03 \x01(\x0e\x32\x18.device.v1.ChannelStates\x12+\n\tchannel_2\x18\x04 \x01(\x0e\x32\x18.device.v1.ChannelStates\x12\x13\n\x0btemperature\x18\x05 \x01(\x02\x12\x10\n\x08pressure\x18\x06 \x01(\x02\x12\x10\n\x08humidity\x18\x07 \x01(\x02\"@\n\x04Info\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0b\n\x03mac\x18\x02 \x01(\t\x12\x10\n\x08\x62le_name\x18\x03 \x01(\t\x12\r\n\x05token\x18\x04 \x01(\t\"\x96\x01\n\rClientMessage\x12&\n\x08get_info\x18\x01 \x01(\x0b\x32\x12.device.v1.GetInfoH\x00\x12(\n\tset_state\x18\x02 \x01(\x0b\x32\x13.device.v1.SetStateH\x00\x12(\n\tget_state\x18\x03 \x01(\x0b\x32\x13.device.v1.GetStateH\x00\x42\t\n\x07message\"\x8b\x01\n\x12\x43ontrollerResponse\x12\x1f\n\x04info\x18\x01 \x01(\x0b\x32\x0f.device.v1.InfoH\x00\x12!\n\x05state\x18\x02 \x01(\x0b\x32\x10.device.v1.StateH\x00\x12%\n\x06status\x18\x03 \x01(\x0e\x32\x13.device.v1.StatusesH\x00\x42\n\n\x08response*\x1d\n\x08Statuses\x12\x06\n\x02Ok\x10\x00\x12\t\n\x05\x45rror\x10\x01*\x1e\n\x0bLightStates\x12\x06\n\x02On\x10\x00\x12\x07\n\x03Off\x10\x01*%\n\x0e\x44oorLockStates\x12\x08\n\x04Open\x10\x00\x12\t\n\x05\x43lose\x10\x01*.\n\rChannelStates\x12\r\n\tChannelOn\x10\x00\x12\x0e\n\nChannelOff\x10\x01*\x8a\x01\n\x06States\x12\x0b\n\x07LightOn\x10\x00\x12\x0c\n\x08LightOff\x10\x01\x12\x10\n\x0c\x44oorLockOpen\x10\x02\x12\x11\n\rDoorLockClose\x10\x03\x12\x0e\n\nChannel1On\x10\x04\x12\x0f\n\x0b\x43hannel1Off\x10\x05\x12\x0e\n\nChannel2On\x10\x06\x12\x0f\n\x0b\x43hannel2Off\x10\x07\x42\x08Z\x06./;apib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'get_data_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\006./;api'
  _STATUSES._serialized_start=738
  _STATUSES._serialized_end=767
  _LIGHTSTATES._serialized_start=769
  _LIGHTSTATES._serialized_end=799
  _DOORLOCKSTATES._serialized_start=801
  _DOORLOCKSTATES._serialized_end=838
  _CHANNELSTATES._serialized_start=840
  _CHANNELSTATES._serialized_end=886
  _STATES._serialized_start=889
  _STATES._serialized_end=1027
  _IDENTIFYREQUEST._serialized_start=29
  _IDENTIFYREQUEST._serialized_end=61
  _GETSTATE._serialized_start=63
  _GETSTATE._serialized_end=73
  _GETINFO._serialized_start=75
  _GETINFO._serialized_end=84
  _SETSTATE._serialized_start=86
  _SETSTATE._serialized_end=130
  _STATE._serialized_start=133
  _STATE._serialized_end=375
  _INFO._serialized_start=377
  _INFO._serialized_end=441
  _CLIENTMESSAGE._serialized_start=444
  _CLIENTMESSAGE._serialized_end=594
  _CONTROLLERRESPONSE._serialized_start=597
  _CONTROLLERRESPONSE._serialized_end=736
# @@protoc_insertion_point(module_scope)
